name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name resumewebsite001 --connection-string 'DefaultEndpointsProtocol=https;AccountName=resumewebsite001;AccountKey=bCqz/GNX8ew70s9CSsQNrtLJbo1SaY2lAdUsctkJxDOGsKbqD2J+TOcb3kLL3O/XpzMI5nDX2OH6+AStZjbC6A==;EndpointSuffix=core.windows.net' --auth-mode key -d '$web' -s .
   # - name: Purge CDN endpoint
   #   uses: azure/CLI@v1
   #   with:
   #     inlineScript: |
   #        az cdn endpoint purge --content-paths  "/*" --profile-name "CDN-ResumeWebsite-EastUS-001"   --name "https://CDN-ResumeWebsite-002.azureedge.net" --resource-group "Storage-ResumeWebsite-EastUS-001"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
